config/routes.rb
Rails.application.routes.draw do
  resources :donos
  resources :estacionamentos
  resources :funcionarios
  resources :usuarios
  resources :veiculos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dono.rb
class Dono < ApplicationRecord
    has_many :estacionamentos, class_name: "estacionamento", foreign_key: "reference_id"
    it { should belong_to(:pessoa) } 
end

app/controllers/donos_controller.rb
class DonosController < ApplicationController
  before_action :set_dono, only: [:show, :edit, :update, :destroy]

  # GET /donos
  # GET /donos.json
  def index
    @donos = Dono.all
  end

  # GET /donos/1
  # GET /donos/1.json
  def show
  end

  # GET /donos/new
  def new
    @dono = Dono.new
  end

  # GET /donos/1/edit
  def edit
  end

  # POST /donos
  # POST /donos.json
  def create
    @dono = Dono.new(dono_params)

    respond_to do |format|
      if @dono.save
        format.html { redirect_to @dono, notice: 'Dono was successfully created.' }
        format.json { render :show, status: :created, location: @dono }
      else
        format.html { render :new }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donos/1
  # PATCH/PUT /donos/1.json
  def update
    respond_to do |format|
      if @dono.update(dono_params)
        format.html { redirect_to @dono, notice: 'Dono was successfully updated.' }
        format.json { render :show, status: :ok, location: @dono }
      else
        format.html { render :edit }
        format.json { render json: @dono.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donos/1
  # DELETE /donos/1.json
  def destroy
    @dono.destroy
    respond_to do |format|
      format.html { redirect_to donos_url, notice: 'Dono was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dono
      @dono = Dono.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dono_params
      params.fetch(:dono, {})
    end
end

app/helpers/donos_helper.rb
module DonosHelper
end

app/views/donos/_form.html.erb
<%= form_with(model: dono, local: true) do |form| %>
  <% if dono.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dono.errors.count, "error") %> prohibited this dono from being saved:</h2>

      <ul>
      <% dono.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/donos/edit.html.erb
<h1>Editing Dono</h1>

<%= render 'form', dono: @dono %>

<%= link_to 'Show', @dono %> |
<%= link_to 'Back', donos_path %>

app/views/donos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donos.each do |dono| %>
      <tr>
        <td><%= link_to 'Show', dono %></td>
        <td><%= link_to 'Edit', edit_dono_path(dono) %></td>
        <td><%= link_to 'Destroy', dono, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dono', new_dono_path %>

app/views/donos/new.html.erb
<h1>New Dono</h1>

<%= render 'form', dono: @dono %>

<%= link_to 'Back', donos_path %>

app/views/donos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dono_path(@dono) %> |
<%= link_to 'Back', donos_path %>