config/routes.rb
Rails.application.routes.draw do
  resources :donos
  resources :estacionamentos
  resources :funcionarios
  resources :usuarios
  resources :veiculos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:Nome, :Idade, :Cpf, :Sexo, :Endereco)
    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :Nome %>
  </div>

  <div class="field">
    <%= form.label :Idade %>
    <%= form.number_field :Idade %>
  </div>

  <div class="field">
    <%= form.label :Cpf %>
    <%= form.text_field :Cpf %>
  </div>

  <div class="field">
    <%= form.label :Sexo %>
    <%= form.text_field :Sexo %>
  </div>

  <div class="field">
    <%= form.label :Endereco %>
    <%= form.text_field :Endereco %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Cpf</th>
      <th>Sexo</th>
      <th>Endereco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.Nome %></td>
        <td><%= pessoa.Idade %></td>
        <td><%= pessoa.Cpf %></td>
        <td><%= pessoa.Sexo %></td>
        <td><%= pessoa.Endereco %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.Nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @pessoa.Idade %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @pessoa.Cpf %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @pessoa.Sexo %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @pessoa.Endereco %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>