config/routes.rb
Rails.application.routes.draw do
  resources :donos
  resources :estacionamentos
  resources :funcionarios
  resources :usuarios
  resources :veiculos
  resources :pessoas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estacionamento.rb
class Estacionamento < ApplicationRecord
    has_many :funcionarios, class_name: "funcionario", foreign_key: "reference_id"
    has_many :usuarios, class_name: "usuario", foreign_key: "reference_id"
    it { should belong_to(  :dono) } 
end

app/controllers/estacionamentos_controller.rb
class EstacionamentosController < ApplicationController
  before_action :set_estacionamento, only: [:show, :edit, :update, :destroy]

  # GET /estacionamentos
  # GET /estacionamentos.json
  def index
    @estacionamentos = Estacionamento.all
  end

  # GET /estacionamentos/1
  # GET /estacionamentos/1.json
  def show
  end

  # GET /estacionamentos/new
  def new
    @estacionamento = Estacionamento.new
  end

  # GET /estacionamentos/1/edit
  def edit
  end

  # POST /estacionamentos
  # POST /estacionamentos.json
  def create
    @estacionamento = Estacionamento.new(estacionamento_params)

    respond_to do |format|
      if @estacionamento.save
        format.html { redirect_to @estacionamento, notice: 'Estacionamento was successfully created.' }
        format.json { render :show, status: :created, location: @estacionamento }
      else
        format.html { render :new }
        format.json { render json: @estacionamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estacionamentos/1
  # PATCH/PUT /estacionamentos/1.json
  def update
    respond_to do |format|
      if @estacionamento.update(estacionamento_params)
        format.html { redirect_to @estacionamento, notice: 'Estacionamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @estacionamento }
      else
        format.html { render :edit }
        format.json { render json: @estacionamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estacionamentos/1
  # DELETE /estacionamentos/1.json
  def destroy
    @estacionamento.destroy
    respond_to do |format|
      format.html { redirect_to estacionamentos_url, notice: 'Estacionamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estacionamento
      @estacionamento = Estacionamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estacionamento_params
      params.require(:estacionamento).permit(:Vagas, :Planos, :Valor_h, :Lucro_Bruto, :Lucro_Liquido, :Gastos)
    end
end

app/helpers/estacionamentos_helper.rb
module EstacionamentosHelper
end

app/views/estacionamentos/_form.html.erb
<%= form_with(model: estacionamento, local: true) do |form| %>
  <% if estacionamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estacionamento.errors.count, "error") %> prohibited this estacionamento from being saved:</h2>

      <ul>
      <% estacionamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Vagas %>
    <%= form.number_field :Vagas %>
  </div>

  <div class="field">
    <%= form.label :Planos %>
    <%= form.text_field :Planos %>
  </div>

  <div class="field">
    <%= form.label :Valor_h %>
    <%= form.number_field :Valor_h %>
  </div>

  <div class="field">
    <%= form.label :Lucro_Bruto %>
    <%= form.number_field :Lucro_Bruto %>
  </div>

  <div class="field">
    <%= form.label :Lucro_Liquido %>
    <%= form.number_field :Lucro_Liquido %>
  </div>

  <div class="field">
    <%= form.label :Gastos %>
    <%= form.number_field :Gastos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estacionamentos/edit.html.erb
<h1>Editing Estacionamento</h1>

<%= render 'form', estacionamento: @estacionamento %>

<%= link_to 'Show', @estacionamento %> |
<%= link_to 'Back', estacionamentos_path %>

app/views/estacionamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estacionamentos</h1>

<table>
  <thead>
    <tr>
      <th>Vagas</th>
      <th>Planos</th>
      <th>Valor h</th>
      <th>Lucro bruto</th>
      <th>Lucro liquido</th>
      <th>Gastos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estacionamentos.each do |estacionamento| %>
      <tr>
        <td><%= estacionamento.Vagas %></td>
        <td><%= estacionamento.Planos %></td>
        <td><%= estacionamento.Valor_h %></td>
        <td><%= estacionamento.Lucro_Bruto %></td>
        <td><%= estacionamento.Lucro_Liquido %></td>
        <td><%= estacionamento.Gastos %></td>
        <td><%= link_to 'Show', estacionamento %></td>
        <td><%= link_to 'Edit', edit_estacionamento_path(estacionamento) %></td>
        <td><%= link_to 'Destroy', estacionamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estacionamento', new_estacionamento_path %>

app/views/estacionamentos/new.html.erb
<h1>New Estacionamento</h1>

<%= render 'form', estacionamento: @estacionamento %>

<%= link_to 'Back', estacionamentos_path %>

app/views/estacionamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vagas:</strong>
  <%= @estacionamento.Vagas %>
</p>

<p>
  <strong>Planos:</strong>
  <%= @estacionamento.Planos %>
</p>

<p>
  <strong>Valor h:</strong>
  <%= @estacionamento.Valor_h %>
</p>

<p>
  <strong>Lucro bruto:</strong>
  <%= @estacionamento.Lucro_Bruto %>
</p>

<p>
  <strong>Lucro liquido:</strong>
  <%= @estacionamento.Lucro_Liquido %>
</p>

<p>
  <strong>Gastos:</strong>
  <%= @estacionamento.Gastos %>
</p>

<%= link_to 'Edit', edit_estacionamento_path(@estacionamento) %> |
<%= link_to 'Back', estacionamentos_path %>